version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    ports:
      - "8000:8000"

  authz-service:
    build:
      context: ./authz
      dockerfile: service/Dockerfile
    networks:
      - envoymesh

  upstream-service:
    build:
      context: ./upstream
      dockerfile: service/Dockerfile
    networks:
      - envoymesh
    ports:
      - "8080:8080"

  zipkin:
    image: openzipkin/zipkin
    networks:
      envoymesh:
        aliases:
          - zipkin
    ports:
      - "9411:9411"

networks:
  envoymesh: {}
