apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    lua_scripts: |
      function envoy_on_response(response_handle)
        local response_body = response_handle:body(true)
        local headers, body = response_handle:httpCall(
          "cluster_example_auth_default_8080_default",
          {
            [":method"] = "POST",
            [":path"] = "/response",
            [":authority"] = "lua_cluster"
          },
          response_body:getBytes(0, response_body:length()),
          5000, true)
        response_handle:headers():add("Lua-Scripts-Enabled", "Processed")
      end
