apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    lua_scripts: |
      function envoy_on_response(response_handle)
        local headers, body = response_handle:httpCall(
          "cluster_example_auth_default_8080_default",
          {
            [":method"] = "GET",
            [":path"] = "/response",
            #["Content-Type"] = "application/json"
          },
          "", #"Hello, hello, is there anybody out there?",
          5000
        )
        response_handle:headers():add("Lua-Scripts-Enabled", "Processed")
      end
