---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "example-auth.default:9001"
  proto: grpc
  include_body:
    max_bytes:  4096
    allow_partial: true
