---
apiVersion: v1
kind: Service
metadata:
  name: example-auth
spec:
  type: ClusterIP
  selector:
    app: example-auth
  ports:
  - port: 9001
    name: http-example-auth
    targetPort: http-api
  - port: 8080
    protocol: TCP
    name: response-capture
    targetPort: response
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: example-auth
  template:
    metadata:
      labels:
        app: example-auth
    spec:
      containers:
      - name: example-auth
        image: rnburn/ambassador-authz:0.10
        imagePullPolicy: Always
        env:
        - name: HT_AUTHZ_PROPAGATION_MODE
          value: B3
        ports:
        - name: http-api
          containerPort: 9001
        - name: response
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
